include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true 
    prefer_single_quotes: true
    always_use_package_imports: true
    always_put_required_named_parameters_first: true
    await_only_futures: true
    file_names: true
    require_trailing_commas: true