// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEz5RMRJpjJc-R5OCfy6m1n8Dcfn7RRf8',
    appId: '1:570293636845:web:8bd09b81a68bb8805646e4',
    messagingSenderId: '570293636845',
    projectId: 'task-managment-75146',
    authDomain: 'task-managment-75146.firebaseapp.com',
    storageBucket: 'task-managment-75146.firebasestorage.app',
    measurementId: 'G-CG51DDGJVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrwBgQv43Jywd302WujHt_xbbsbAeM3lo',
    appId: '1:570293636845:android:90d84d62c97b85a25646e4',
    messagingSenderId: '570293636845',
    projectId: 'task-managment-75146',
    storageBucket: 'task-managment-75146.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkaUwLFVuEbL1GrWxaybl3muqDv3hn2sg',
    appId: '1:570293636845:ios:2ad23eac75cb20c45646e4',
    messagingSenderId: '570293636845',
    projectId: 'task-managment-75146',
    storageBucket: 'task-managment-75146.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkaUwLFVuEbL1GrWxaybl3muqDv3hn2sg',
    appId: '1:570293636845:ios:2ad23eac75cb20c45646e4',
    messagingSenderId: '570293636845',
    projectId: 'task-managment-75146',
    storageBucket: 'task-managment-75146.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEz5RMRJpjJc-R5OCfy6m1n8Dcfn7RRf8',
    appId: '1:570293636845:web:2e1803cd28c79b845646e4',
    messagingSenderId: '570293636845',
    projectId: 'task-managment-75146',
    authDomain: 'task-managment-75146.firebaseapp.com',
    storageBucket: 'task-managment-75146.firebasestorage.app',
    measurementId: 'G-HZX6T3Y0C9',
  );
}
